### ISSUE TITLE
ciano converts nothing: "error: invalid argument"

### ISSUE THREAD

**Issue by glaubersm** [flathub/com.github.robertsanseries.ciano#1]
everytime I try convert something I get the error  message
"error: invalid argument"

I use Arch Linux, flatpak  0.10.2.1-2

**Comment by nedrichards** [comment]
Yeah, trying to convert an MP4 file to WEBM I got that error, and on the command line:

> ** (com.github.robertsanseries.ciano:3): WARNING **: ConverterController.vala:280: Error: Child process exited with code 1

**Comment by robertsanseries** [comment]
@glaubersm @nedrichards I'm going to download arch linux to test! I did not test in this operating system.

**Comment by nedrichards** [comment]
I'm not on Arch. I'm using Endless OS 3.3.9

**Comment by robertsanseries** [comment]
@nedrichards well i had only done testing on fedora and debian (ubuntu/elementary/mint)... I'll try to verify this as soon as possible.

**Comment by lmintmate** [comment]
Same problem here. In addition to the "Error: Invalid argument" message, which I get when trying to convert music, when I try to convert video I get "Error: Invalid data found when processing input". I have Linux Mint 18.3, with Flatpak 0.10.0. I do hope this issue gets fixed, as your application looks very promising, especially as there aren't many gui multimedia file converters in Linux.

**Comment by robertsanseries** [comment]
@lmintmate I'm already working on it.

**Comment by LeandroStanger** [comment]
@robertsanseries How is the progress of the correction?

**Comment by robertsanseries** [comment]
@LeandroStanger Sorry for the delay, I'll try to release until the 25th.

**Comment by CesarLinuxx** [comment]
waiting translate to Portuguese pt-br

**Comment by CesarLinuxx** [comment]
The same problem here.  error: Invalid data found when processing input "mint 18.3"

**Comment by robertsanseries** [comment]
The error that is generating this problem is in the FFMPEG execution:

`[NULL @ 0x1791b00] Unable to find a suitable output format`

If I try to run the command directly on the terminal everything works correctly!

**Comment by CesarLinuxx** [comment]
certo ansioso para correção

**Comment by nedrichards** [comment]
This should be fixed by https://github.com/flathub/com.github.robertsanseries.ciano/commit/c2a3f7a0b63b1868f3c39325b4021ef76f162971 in my testing. There's still some stuff that probably needs to be fixed in ffmpeg (e.g. it may not have all the correct libraries for the conversion pairs the app exposes) but it should at least be using the bundled ffmpeg now.

**Comment by CesarLinuxx** [comment]
como estão as Novidades ?

**Comment by glaubersm** [comment]
Escreva em inglês.
Em português acho que ninguém vai te entender haha.

**Comment by CesarLinuxx** [comment]
How are the news?
