### ISSUE TITLE
Include elementary themes

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.github.robertsanseries.ciano#2]
Given that the app requires the elementary icon theme and you can't guarantee that's on a flathub users device then you should bundle it in the app.

You may want to do the same for the GTK theme as well whilst you're at it - since that's the only way to ensure you'll be pixel perfect.

**Comment by robertsanseries** [comment]
@nedrichards thanks for the tip!

**Comment by jurf** [comment]
It doesn’t use the theme however, maybe override that with an env var?

**Comment by TingPing** [comment]
Application should be patched to modify GtkSettings in startup.

**Comment by robertsanseries** [comment]
@TingPing I'm testing locally! however it is generating the following error: 
```
Applying patch elementary-theme.patch
patching file src/Main.vala
Hunk #1 FAILED at 27.
1 out of 1 hunk FAILED -- saving rejects to file src/Main.vala.rej
Error: module ciano: Processo filho concluiu com código 1
```

**File elementary-theme.patch**
```
--- a/src/Main.vala	2018-05-19 09:26:30.880947471 -0100
+++ b/src/Main.vala	2018-05-19 09:26:50.505230258 -0100
@@ -27,6 +27,7 @@

	public static void main (string [] args) {
		var app = new Ciano.Application ();
+               Gtk.Settings.get_default().set_property("gtk-theme-name", "elementary");
		app.run (args);
	}
```

how to generate this file correctly?

**Comment by TingPing** [comment]
Personally I just checkout the correct release in `git`, make and commit the change, `git format-patch HEAD~1`

**Comment by robertsanseries** [comment]
I did the installation successfully, but theme is not displayed yet!   commits: 06589ac8259be2f3c909f14bd0407a920a5bf751  and 8e320e35e272a6d692eaa3ad88a60fb3044b9ebf

**Comment by TingPing** [comment]
Try putting it in `Application.vala` in the `startup` handler.

**Comment by TingPing** [comment]
(Also please it locally before just pushing patches)

**Comment by robertsanseries** [comment]
perfect @TingPing! Thank you for your support! For me it worked correctly!

**Comment by robertsanseries** [comment]
I await your feedback to close this issue!

**Comment by jurf** [comment]
Works for me, thanks! Ciano no longer looks broken.
